### PR TITLE
Hv joboptionfix

### PR DESCRIPTION
**Pull request by HansVRP**
-debugged the UDP.

- transfered the UDP from python script to notebook

- centralized the pre and post processing pipeline

### CODE REVIEW

**Comment by HansVRP** [comment]
@clausmichele

**Comment by clausmichele** [comment]
Hi @HansVRP, thanks for the improvements!
I managed to create the UDP:
image

But it is possible to have the spatial_extent selection to appear in the same way as it would be for load_collection?
Instead of:
image
something like:
image

If not, doesn't matter it's already good like this.

**Comment by HansVRP** [comment]
Ah yes that should be possible, 

I set up the parameter input to accept input coordinates. But input polygons is possible as well. 
Let me check.

**Comment by clausmichele** [comment]
The best would be to mimic the parameter of the `filter_bbox`, which handles bounding boxes only and not polygons (to keep it easy):
image

**Comment by HansVRP** [comment]
@clausmichele parameterized input was changed from coordinates to bbox in the UDP, which should fit your need

**Pull request merged**
